pod 'XBExtension', '~> 0.3'
pod 'SDWebImage', '~> 3.7'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'FBPLUGIN', '~>0.2.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.5'
pod 'hpple', '~> 0.2'
pod 'DLAlertView'